### ISSUE TITLE
[GUI] Copy/Paste feature is not implemented.

### ISSUE THREAD

**Issue by kdesnos** [preesm/preesm#10]
Implementing the copy/paste feature such that:
- One or several actors can be copied with their ports.
- If a group of interconnected actors is copied, the fifos are also pasted with the actors.

Special care must be taken so that if the name of a pasted actor is identical to one of the actors already present in the graph, the pasted actor is automatically renamed.

**Comment by antoine-morvan** [comment]
https://github.com/preesm/preesm/commit/f4b2798c56db3d636b7d3d63b237cb5e33f9638d adds it.
