### ISSUE TITLE
Unclear error if generating .diagram from .pi with wrong PiSDF refinements

### ISSUE THREAD

**Issue by ahonorat** [preesm/preesm#101]
The diagram corresponding to a dummy.pi cannot be generated if dummy.pi contains refinements to not existing .pi files. A Null pointer exception occurs giving no clue about what is actually wrong.

It could be better to test if .pi refinements exist before beginning the transformation. This would generate a comprehensible error.

**Comment by antoine-morvan** [comment]
Please provide (and attach) a complete and if possible minimal example to reproduce.

**Comment by ahonorat** [comment]
Could not reproduce anymore, most probably fixed by 08e43d709244629c43180fcee7a228acd1a0f1cf .
