### ISSUE TITLE
Wrong number of _PREESM_NBTHREADS_ when using more than one printer

### ISSUE THREAD

**Issue by leos313** [preesm/preesm#113]
When using different kind of core_types (which use different printers and **not** the same one), the generated `_PREESM_NBTHREADS_` variable is wrong as well as the number of computation thread functions and the number of `launch` of threads (inside the `main.c` file only).

This is because the final printed `main.c` is the one associated with the last printer used by the Codegen.

For instance, inside the function `printMain()` of the `CPrinter`, the variable `printerBlocks.size` is used (which means that only the number of cores of the same printer are taken into account). 

To avoid the problem, the total number of `CodegenEngine.codeBlocks` could be used.

**Comment by kdesnos** [comment]
Thanks for notifying us of this issue.

I think at the moment, you're the only one experimenting with code generation with both thread based and non-thread based code generation Printers.

If using the `CodegenEngine.codeBlocks` seems to solve the issue for you, while keeping the current behavior for the scenario where "homogeneous" printers are used, you can push this in your code and create a pull request for it to be integrated to Preesm.
(Make sure you rebase your branch on latest commits from the Preesm repository before doing that).
