### ISSUE TITLE
Cutting the loop in generated code

### ISSUE THREAD

**Issue by alemehghasemi** [preesm/preesm#119]
Hello,

Apparently Preesm put the application inside an infinite loop.
How can I change the generated code to cut the loop so that it just displays the video in its original time for instance for Jaguar mp4, 15 seconds?
Or maybe I should change timing ?
Thank you in advance.

Alemeh,

**Comment by antoine-morvan** [comment]
Hi, 

In the user header **preesm.h**, you can define the preprocessor constant ```LOOP_SIZE```.

For the video applications, each iteration of the loop will display 1 frame. So for 15s at 30 fps, you will have to set this loop size to 15*30 = 750
```
#define LOOP_SIZE 750
```

**Comment by alemehghasemi** [comment]
Thank you Antoin for your help.

**Comment by alemehghasemi** [comment]
Thank you so much Antoine for your help.
