### ISSUE TITLE
Actor firing latencies set in scenario is not taken into account in the Gantt chart

### ISSUE THREAD

**Issue by mpelcat** [preesm/preesm#121]
With Preesm 3.4, all actors stick to 100 cycles while timings are correctly set in scenario.

[stereo.zip](https://github.com/preesm/preesm/files/2992192/stereo.zip)

**Comment by leos313** [comment]
Some more info that can help to find the problem:
 * the problem is present also with the old version of PREESM (for instance the 3.1.3 has the same problem)
 * the actor firing latencies are not taken into account nor for the Gantt nor for the scheduling

**Comment by antoine-morvan** [comment]
see https://github.com/preesm/preesm/issues/132
