### ISSUE TITLE
Can the workflow be run in a stand-alone fashion?

### ISSUE THREAD

**Issue by LowellHuawei** [preesm/preesm#124]
Our application may require fairly large PiSDF diagrams -- and possibly a very large number of them.    We are hoping to automatically generate them, to some extent at least, and simulate them using PREESM.  We would also like to use automated regression testing as well.  

Can we generate the .pi files, the .scenario files, and possibly the workflow files, outside of PREESM and then run the workflow by a script?

**Comment by antoine-morvan** [comment]
Hi, 

I think you are looking for this: https://github.com/preesm/preesm-cli

Best.

**Comment by LowellHuawei** [comment]
Thanks!
