### ISSUE TITLE
does exclipse or preesm download things from the internet as it runs?

### ISSUE THREAD

**Issue by LowellHuawei** [preesm/preesm#127]
I'm just curious if it is necessary to have full, non-firewalled access to the internet in order to use PREESM or any of the tools that it uses.

**Comment by antoine-morvan** [comment]
Hi, 

No, you don't (well, should not...) need Internet access to run Preesm.

You need when building it from source (Maven and Eclipse).

**Comment by antoine-morvan** [comment]
Erratum: You also need Internet when installing from Update Site.
