### ISSUE TITLE
Update timings in Preesm

### ISSUE THREAD

**Issue by antoine-morvan** [preesm/preesm#132]
Timings in Preesm are no good:

1. The scenario editor does not allow giving different timings to different instances of an actor. This is an issue since different instances with different parameter values might have different execution time (see https://github.com/preesm/preesm/issues/77);
2. The scenario editor does not allow giving parameterized timings. Although instrumentation might never generated parameterized timings, the user might now the complexity of his own code (see https://github.com/preesm/preesm/issues/73);
3. The scenario editor cannot import instrumentation results as is: the exported CSV must be processed manually in order to import timings properly. This must be fixed (see https://github.com/preesm/preesm/issues/52);
4. The new instrumentation library (dump.c/h) has to be tested on C6678 (see https://github.com/preesm/preesm/issues/95);
5. Timings seem to not be properly propagated to all steps (see https://github.com/preesm/preesm/issues/121);

**Comment by antoine-morvan** [comment]
2 first bullets are fixed since https://github.com/preesm/preesm/commit/42b11efd4781881b754a9f05b25a77e9eddf464d.

**Comment by leos313** [comment]
Hi Guys,

What is new on this bug? Are the 3 last points still open?

Thanks

**Comment by antoine-morvan** [comment]
Points 1 and 2 are fixed in latest release. Alexandre H. is working on points 3 and 4. It's up to the scheduler to use the timing information. The Gantt exporter should be using them as of latest release.

**Comment by ahonorat** [comment]
All related issues have been closed, and new timings seem to work (specification, instrumentation, and parsing) since bd8fe33 , thus the issue can be closed.
