### ISSUE TITLE
[Codegen] Gather multiple copies of support library source files in one place.

### ISSUE THREAD

**Issue by kdesnos** [preesm/preesm#14]
Currently, each preesm project possess its own copy of the following support library files. 
- clock.h, ~.c
- communication.h, ~.c
- dump.h, ~.c
- fifo.h, ~.c
- x86.h
- memory.h, ~.c
- main.c

When one of this file is modified, all its locations must be updated manually in each application project.

I think these files should be automatically "copied" from a unique location into the application directory during the execution of a workflow containing a code generation task. Moreover, since these files are different depending on the target and the code generator, only the appropriate files could be "copied" for each preesm project.

**Comment by antoine-morvan** [comment]
Fixed since https://github.com/preesm/preesm/commit/5c6c7cf7e9cf8744c427e9195c76407954821056
