### ISSUE TITLE
Multiple memory not taken into account

### ISSUE THREAD

**Issue by leos313** [preesm/preesm#140]
When defining multiple memory nodes connected together in the slam architecture, code generation does not seem to take this information into account.

The additional memory is simply ignored. No error/warning messages are printed.

Attached slam for reproduction.
[ARTICo3_4.slam.zip](https://github.com/preesm/preesm/files/3116673/ARTICo3_4.slam.zip)

**Comment by kdesnos** [comment]
Hi Leo,
The way distributed memory is currently taken into account is "hardcoded" in the memory allocation task. So yes, you're right, at the moment, putting several memories in the  slam has no effect.

To allocate memory in distributed memory, the 4 memory organization currently available are listed [in the documentation of the memory allocation task, with the values for the "distribution" parameter](https://preesm.github.io/docs/workflowtasksref/#memory-allocation).

More details on this topic is available in the [following publication](https://hal.archives-ouvertes.fr/hal-01390486/document).
