### ISSUE TITLE
(Codegen-Hardware) Compatibility with Papify to be tested

### ISSUE THREAD

**Issue by leos313** [preesm/preesm#145]
Compatibility of the Hardware Printer with Papify should be checked and, in case, fixed. Other features related to "custom register events" on the Hardware side may require a double check.

**Comment by dmadronal** [comment]
I have isolated PapifyAction and PapifyFunctionCall in different classes/printers than the Buffer and FunctionCall classes (previously employed by PAPIFY).

In papifyDevelop branch I have fixed all the incompatibilities I found. To be checked once this branch is merged on develop branch.

**Comment by leos313** [comment]
ARTICo³ works properly with PAPIFY after the last commits.
