### ISSUE TITLE
what is ABC in LatencyABC analysis?

### ISSUE THREAD

**Issue by LowellHuawei** [preesm/preesm#147]
I can't find that term in google...

Thanks,
   Lowell

**Comment by mpelcat** [comment]
Dear Lowell,

ABC is a creation of us, there is a paper here: https://www.date-conference.com/proceedings-archive/PAPERS/2009/DATE09/PDFFILES/IP5_02.PDF

Best Regards,
Maxime

**Comment by LowellHuawei** [comment]
Thanks!
