### ISSUE TITLE
[TUTO] Workflow task error

### ISSUE THREAD

**Issue by ggendro** [preesm/preesm#149]
When doing tutorial Memory Footprint on the official website of Preesm, there is an error message for workflow task "DisplayGantt":
Plugin associated to the workflow task not found.	Codegen.workflow	/org.ietr.preesm.sobel/Workflows	org.ietr.preesm.mapper.plot.GanttEditor	Problem

**Comment by antoine-morvan** [comment]
What version of Preesm are you using ?
Could you attach a zip with the project you are using ?

**Comment by antoine-morvan** [comment]
Duplicate of #134 fixed with v3.7.0
