### ISSUE TITLE
GUI problems on the scenario editor - Preesm 3.10 - XUbuntu

### ISSUE THREAD

**Issue by mpelcat** [preesm/preesm#160]
When we click on one value in a scenario table to modify it (for example an expression in the timing tab of the scenario), no cursor appears. When the value is modified (deleting or adding characters), nothing visual happens and the updates (visual and effective) appear only when we press the "Enter" key on keyboard. Also, pressing Ctrl+S does not save the scenario (the "star" remains displayed - still need to save) and we need to close the scenario for Eclipse to request "do you want to save before closing".

Preesm version: 3.10
OS: XUbuntu 16.04

**Comment by antoine-morvan** [comment]
Hi,

It's an issue with GTK versions prior to 3.20 (see https://bugs.eclipse.org/bugs/show_bug.cgi?id=531928). Ubuntu 16.04 (and variants like Xubuntu) have GTK 3.18. I'd suggest updating to Ubuntu 18.04 at least.
