### ISSUE TITLE
(PiWriter) getPeriod on a PiGraph still throw a NullPointer exeception

### ISSUE THREAD

**Issue by dylangageot** [preesm/preesm#161]
When prototyping Clustering algorithm with Hierarchical actors building, it cannot be exported with PiSDFExporter because of NPE when calling method getPeriod() on originalActor. I have attached the PREESM project and corresponding commit to reproduce this behavior.

![NPE with call stack](https://user-images.githubusercontent.com/5111951/60161966-d7388580-97f8-11e9-8635-a472ce7096f2.png)

```java
    vertexElt.setAttribute(PiIdentifiers.NODE_KIND, PiIdentifiers.ACTOR);
    final Expression period = originalActor.getPeriod(); // line 332
    if (period != null) {
      vertexElt.setAttribute(PiIdentifiers.ACTOR_PERIOD, period.getExpressionAsString());
    }
```
[PREESM project to reproduce error](https://github.com/preesm/preesm/files/3328933/org.ietr.preesm.apgan.zip)

[Commit on which error appear](https://github.com/preesm/preesm/commit/348857ae8f7589a65e596db979ff00503b623d1c)

**Comment by antoine-morvan** [comment]
TODO: Add support in the PiWriter for generated hierarchy: on the fly creation of actor with refinment with generated URL.
