### ISSUE TITLE
[UI] associating header file to a PiSDF graph

### ISSUE THREAD

**Issue by leos313** [preesm/preesm#165]
When associating a header file to a specific actor within a PiSDF diagram, all the controls related with the variable names are performed (i.e. if the name of the actor interfaces match with the variable name within the function declared in the header file).
It can be nice to have control (i.e. if the names match) also on the data-type of the variables: different functions (which have the same variable-names but different data-type) can be associated to the same actor and the type declared in the tab `Properties` of the FIFOs is ignored.

**Comment by ahonorat** [comment]
Ok, this has been implemented in my current branch, will be merged in master branch sooner or later.
Thanks for reporting us this bug (and sorry for the 2 years delay!).

Another feature has been implemented at the same time: user special actors (broadcast/roundbuffer/fork/join) should also have the same type of fifo on all their I/O; this is checked now.

Note that this request led to a refactor of the PiGraph consistence checker, which is now more robust but also more picky. Especially the refinement files have to exist in the flie system.
