### ISSUE TITLE
[PAPIFY tuto] bug in eventLib.c?

### ISSUE THREAD

**Issue by leos313** [preesm/preesm#181]
Context: Using the file that can be downloaded from the PREESM tuto website.
When using `eventLib.c`, all the file saved in output related to the timing, have the value 0 in output.
Following the piece of code responsible:

```
		//papify_PEs_info[PE_id].time_init_action = 0;
		//papify_PEs_info[PE_id].time_end_action = 0;
		printingFile = fopen(output_file_name,"a+");
		fprintf(printingFile, "%s,%s,%lld,%lld\n", papify_PEs_info[PE_id].PE_id, papify_action->actor_id, papify_PEs_info[PE_id].time_init_action, papify_PEs_info[PE_id].time_end_action);
		printf("%llu   ",papify_PEs_info[PE_id].time_init_action);
		printf("  %llu   \n",papify_PEs_info[PE_id].time_end_action);
		fclose(printingFile);
```

I needed to comment the first two line above. If you do not comment them, before saving the value in the output file, it will set the variable to zero.

What I am doing wrong??? am I using the file in a wrong way?

**Comment by antoine-morvan** [comment]
Fixed with https://github.com/preesm/preesm.github.io/commit/8e35590e91935f82d1c30da9aab6cc6b2bd195e0
