### ISSUE TITLE
Execution Time of the 1-core Gantt is not the sum of the precharacterized actors

### ISSUE THREAD

**Issue by ClaudioRubattu** [preesm/preesm#182]
The issue is verifiable considering the attached project (the Sobel tutorial in the repo). 
[sobel_gantt_issue.zip](https://github.com/preesm/preesm/files/3416820/sobel_gantt_issue.zip)

Running the workflow "Codegen_Papify" (*) with the scenarios "SOBEL_1PE_0A7_1A15_Papify_4customActivity" and "SOBEL_1PE_1A7_0A15_Papify_4customActivity", all actors are properly mapped into the only one present core (1 A15 or 1 A7 respectively). However, having precharacterized the timing of the actors, the sum of the weight should correspond to the final execution time, but 200 cycles are added with respect to the expected value.

For instance, regarding the first mentioned scenario, the timing is the following:
![timing](https://user-images.githubusercontent.com/24210476/61625284-a07c5080-ac7a-11e9-9b32-1870526e2d31.PNG)
 
Considering the 4 repeats of the Sobel actor, the sum is 1035.
But in the Gantt appears 1235, as in the figure below.
![final_execution_time](https://user-images.githubusercontent.com/24210476/61625489-29938780-ac7b-11e9-9751-795dc1ff7bb3.PNG)
   
I verified the same offset (200 cycles) in the second scenario. 

(*) : there is not PAPIFY task, and the monitored code generation is properly included into the Codegen task. This just to say this issue should not have any link with PAPIFY context.

**Comment by antoine-morvan** [comment]
Split and Merge actors induce insertion of 1 explode and 1 implode actors in the SRDAG. Those actors have no timingn, thus default timing of 100 is used.

**Comment by antoine-morvan** [comment]
@ClaudioRubattu I've seen the workflow you are using is pretty old and based on the old SDF model. I tried to run the new workflow tasks with your scenario, and the timings of explode/implode nodes are indexed on the memory copy speed.

**Comment by antoine-morvan** [comment]
Using new workflow tasks (scheduling from PiMM), the explode/implode nodes have timings indexed on the memory speed: `timing = (fifo size / memory speed) + mem setup time`
