### ISSUE TITLE
bug in eventLib.h (preprocessor instructions)

### ISSUE THREAD

**Issue by leos313** [preesm/preesm#184]
Within the file `eventLib.h` downloaded from the PREESM Tutorial PAPIFY page:

Line 5:
```
#ifndef EVENT_LIB
#define EVENT_LIB
#endif
```

The preprocessor instruction `#endif` should be inserted at the end of the whole file and not just after the definition of the `EVENT_LIB` variable

**Comment by antoine-morvan** [comment]
Fixed with https://github.com/preesm/preesm.github.io/commit/087742a100eea088e98ede27b955ca56585ee5d5
