### ISSUE TITLE
[Workflow] Add a "Schedulability checking" task

### ISSUE THREAD

**Issue by kdesnos** [preesm/preesm#19]
In the current version, checking the schedulability of an application is done at the beginning of several transformations: single-rate, hierarchy flattening.

Replacing these checks with a task dedicated to checking an IBSDF graphs schedulability would be nice, especially when developing a new application. In such a case, a workflow containing only this new task might be of great help for a developer.

This task could also serve as a basis to implements new checks of the properties of IBSDF ans PiSDF graphs.

**Comment by antoine-morvan** [comment]
Is it related to the modifications brought by the following commit ?
https://github.com/preesm/preesm/commit/739f35f7cd5fb4c34fbff40301ca593304dede54

**Comment by kdesnos** [comment]
Unfortunately no. The checker added in this commit checks the validity of a mapping/scheduling with regards to constraints on the order of communication primitives. The verification mentioned in this issue is about the schedulability (Liveness & Deadlock freness) of the original SDF specification.

**Comment by antoine-morvan** [comment]
Note: this schedulability check task could only work when there is no reconfigurability. With the current intermediate representation, that implies it is only applicable to graphs that do not contain any actor with one or more "Config Output Port".

**Comment by ahonorat** [comment]
The requested menu popup action has been added by b13b3a142fd5ff9cdcd8f315c0853dbac9fc9c65 .
The name is "Check PiSDF Liveness".
The method used is checking if flat PiSDF is acyclic first, if no then the SRDAG is generated and again checked if acyclic.
