### ISSUE TITLE
Error when running workflow if initialization of delay is linked to data interface

### ISSUE THREAD

**Issue by Martayugui** [preesm/preesm#205]
Initialization of a delay using a data interface, generates an error when trying to run the workflow.
The following message appers:

**"SEVERE: Interface interfaceInput does not exist, or is not connect in vertex fatherActor hierarchy"**

Here, there is an evidence to reproduce the error:

![initialization delay by an interface](https://user-images.githubusercontent.com/36645814/63422425-a34d9b00-c40a-11e9-95a4-c9d3fbb3de1d.png)

**Comment by antoine-morvan** [comment]
Reading the log, it seems you are using deprecated workflow tasks PiMM2SDF (see https://preesm.github.io/docs/workflowtasksref/#static-pimm-to-ibsdf---deprecated)

**Comment by Martayugui** [comment]
I took the workflow from a project of my colleagues, I just replaced the deprecated one by the updated version. It works properly.

Now, I would like to use asymetric configuration for delay setter/getter actor, would it be possible to implement it?. In order to avoid the current error, I have to use both of data input/output interfaces in the delay configuration.

**Comment by orlyn44** [comment]
As of now, asymetric configurations are not supported for setter / getter. 
The only possibility for you is to use a "dummy" actor that will consume the tokens in a setter / void configuration or that will produce dummy tokens in a void / getter configuration.
Those actors can be as simple as empty function calls, but they have to be present for the code generation to work.
