### ISSUE TITLE
FIFO creation in pisdf editor

### ISSUE THREAD

**Issue by judicael35** [preesm/preesm#21]
Hello,

It seems there is a bug when trying to add a fifo between two actors in PiSDF editor.

When I want to add a fifo, I can't click on actor and access to the dialog box to enter the output port name. The logo's cursor stay a plug with a crossed circle, but I can click on a existing output port. I don't have this problem for the creation of an input port.

I am on the last released version (update site).

Thank you

**Comment by jheulot** [comment]
The problem still appear when using special actors (Broadcast, Fork, Join, etc..)

**Comment by ClementGGuy** [comment]
This is now corrected.
