### ISSUE TITLE
PiSDFToSingleRate do not consider graph with one actor

### ISSUE THREAD

**Issue by dylangageot** [preesm/preesm#218]
PiSDFToSingleRateTask do not consider graph with only one actor. When PiSDFScheduling is executed, it throws a exception of that kind on the transformed graph:
`13:29:01 SEVERE: Unexpected Exception: java.lang.UnsupportedOperationException:Can not convert an empty graph. Check the refinement for [one_actor].
 Contact Preesm developers if you cannot solve the problem.`

You may think that having one actor in top lovel has no sense, but it could happen from a full graph-clusterization.

Project to reproduce is included. 
[org.ietr.preesm.one_actor.zip](https://github.com/preesm/preesm/files/3555333/org.ietr.preesm.one_actor.zip)

**Comment by antoine-morvan** [comment]
Problem is in the flattener.
