### ISSUE TITLE
PIMM2SDF bad join actor translation

### ISSUE THREAD

**Issue by judicael35** [preesm/preesm#22]
The join actor is not well converted from a Pimm graph to an SDF graph. Its inputs are not in the good order (alphabetical or port order).

I look at the graphs generated after PIMM2SDF workflow element.  So I think the bug is in the plugin org.ietr.preesm.experiment.pimm2sdf.PiMM2SDFTask.

**Comment by antoine-morvan** [comment]
In this hack 2b99f08f20d4762583524bdbad170098d103638d, I replaced all HashSets/HashMaps with LinkedHashSets/LinkedHashMaps so that order on values/keys is kept. Could you check if the issue is still open in latest version ?
