### ISSUE TITLE
Cannot open graphml files with Preesm 3.15.0

### ISSUE THREAD

**Issue by mpelcat** [preesm/preesm#226]
Hi,

Opening any graphml file causes a null pointer exception.

![Capture d’écran de 2019-09-03 08-26-56](https://user-images.githubusercontent.com/1950287/64151960-d3923200-ce2b-11e9-8cba-c0ef7ec96b82.png)

**Comment by antoine-morvan** [comment]
Please provide the graphml file and project to generate it.

**Comment by mpelcat** [comment]
[stereo_top.zip](https://github.com/preesm/preesm/files/3568303/stereo_top.zip)
