### ISSUE TITLE
Cannot export Pi graphs into vector image format

### ISSUE THREAD

**Issue by mpelcat** [preesm/preesm#227]
All possibilities of exports are bitmap, which is not convenient especially for very large graphs.

**Comment by antoine-morvan** [comment]
The SVG export feature has its own entry in the context menu of the PiGraph editor.

However it only appears if no element (actor, fifo, parameter, ...) is selected:
![nothing_selected](https://user-images.githubusercontent.com/18552103/64155984-2ff94f80-ce34-11e9-817f-859f3db00dd1.png)

If something happens to be selected, the entry will not appear (in this screenshot, a dependency is selected): 
![dependency_selected](https://user-images.githubusercontent.com/18552103/64156031-47383d00-ce34-11e9-9d75-ba344ead2108.png)

I'll change the behavior to have the Export SVG entry visible with any selection.
