### ISSUE TITLE
SEVERE: Trying to set a non strictly positive time for vertex when loop

### ISSUE THREAD

**Issue by MariaGarcia7293** [preesm/preesm#234]
I am doing a loop with PREESM, however when I increase the number of iterations of the for loop, this error is displayed. 

"SEVERE: Trying to set a non strictly positive time for vertex"

My implementation only works for 4 or lower number of iterations.

**Comment by ahonorat** [comment]
Hello,

do you have the stack trace of the error? Also, what version of Preesm do you use?
I suspect that you obtained this error because of large numbers in the timings and then an overflow occurs. However, similar bugs have been fixed since version 3.15.

**Comment by MariaGarcia7293** [comment]
This error is already fixed using last version of PREESM (3.17.0). However, making use of the new version of PREESM, I cannot set the refinement inside an actor. 

When I try to do it, there is a NOTICE in my console saying "Could not parse header .h".

Do I should have something into account?,

BR,

María.

**Comment by antoine-morvan** [comment]
Please provide a minimal example to reproduce.

**Comment by MariaGarcia7293** [comment]
I am using the last version of PREESM, and I just "drag-and-drop" the “test.h” file on the corresponding actor in order to assign a function to it. It has been displayed on the console:

![screenshot](https://user-images.githubusercontent.com/32075288/65889269-41853700-e3a1-11e9-8c4f-a147b7482684.png)

**Comment by antoine-morvan** [comment]
Fix will be included in next release (and next released will be published next week).
