### ISSUE TITLE
No possible header file assignation are allowed

### ISSUE THREAD

**Issue by leos313** [preesm/preesm#249]
PREESM 3.17:
when trying to assign an Header file to an actor the following error is prompt always:

```
NOTICE: Could not parse header 'L/spiderApp/Code/include/read_image.h'.

```
Is that coming from something I am doing wrong? 

The `L` at the beginning of the path seem quite strange also.
Same problem with PREESM 3.16. 
Using PREESM 3.14 the problem does not exist and you can assign the header file to the actor.

**Comment by antoine-morvan** [comment]
Fixed in https://github.com/preesm/preesm/issues/234

**Comment by leos313** [comment]
Thank you Antoine! The name of the issue seemed to point to a different problem.
