### ISSUE TITLE
Improve reactivity of the Pi Graph editor

### ISSUE THREAD

**Issue by jheulot** [preesm/preesm#26]
After running the Preesm App connected with the Java Monitor, 
Most of the processing times is spend on decorator computation slowing down a lot the Preesm reactivity.
Most of this decorator computation time is spend in expression checking, it may be good to check it only if the expression (or the depending parameters) are changed.
A lot of performance can be gained with that (I have check it in an ugly way).

**Comment by kdesnos** [comment]
Done since commit c6f73a5f1382
