### ISSUE TITLE
(Codegen) Multiple function calls for the same init fonction refinement

### ISSUE THREAD

**Issue by hmiomand** [preesm/preesm#262]
PREESM generate multiple function calls for the same init function refinement.

In the following example, **NB_ITER_INPUT_PARAM** is set at 100, actor **calibrationLoop** is executed 100 times, and the codegen does 100 calls for **initCalibrationLoop**.
![graphe](https://user-images.githubusercontent.com/26252258/69132448-61d59600-0ab4-11ea-8d56-280e608209f8.png)

PREESM project provided below:
[Basic_Calibration_DI_init_refinement_issue.zip](https://github.com/preesm/preesm/files/3862906/Basic_Calibration_DI_init_refinement_issue.zip)

**Comment by ahonorat** [comment]
Bug will be fixed in next released of Preesm. 
Details of the solution: copy the init refinement during the SRDAG transform only in the first firing of an actor.
