### ISSUE TITLE
Can't import timings from .xls into scenario

### ISSUE THREAD

**Issue by hmiomand** [preesm/preesm#264]
Can't import the timing informations from a .xls file into a scenario.
The **timing.xls** file was generated by filling up timing informations into **1Core.scenario** and using the **Export Timings** option.
Importing this timing file into **2Core.scenario** has no effect.
The generated **timing.xls** seems to be valid.

[Calibration_DI_FP64_example.zip](https://github.com/preesm/preesm/files/3904626/Calibration_DI_FP64_example.zip)

**Comment by ahonorat** [comment]
This will be solved in next release that includes this commit.
