### ISSUE TITLE
Dismissing "Set the Data Type" option on fifos deletes fifo properties.

### ISSUE THREAD

**Issue by hmiomand** [preesm/preesm#267]
When editing a .diagram, dismissing the **Set the Data Type** option (right click on a fifo -> Set the Data Type), either with the red cross or by hitting **Cancel**, deletes the fifo properties (**Data type**, **Source port rate** and **Target port rate**) instead of living them as is.

**Comment by ahonorat** [comment]
Ok, I will probably remove this command from the menu since it is useless (we can edit the data type in the properties section).

**Comment by ahonorat** [comment]
Fixed by commit 3ecb964 .
