### ISSUE TITLE
Scenario doesn't keep mapping constraint if multiple subgraphs have a similar name.

### ISSUE THREAD

**Issue by hmiomand** [preesm/preesm#269]
Scenario doesn't keep mapping constraint if multiple subgraphs have a similar name.
In the provided project, inside **calibrationActor** subgraph, subgraphs having a name starting with **calibrationActor<something>** won't be mapped on any core, as they won't appear as mapped in the **Constraints** tab of the scenario file, despite having the corresponding line appearing in the test representation.

This issue also prevent the Workflow execution.

[Calibration_DI_Hybrid_FP_mapping_constraint_issue.zip](https://github.com/preesm/preesm/files/3927960/Calibration_DI_Hybrid_FP_mapping_constraint_issue.zip)

**Comment by ahonorat** [comment]
Bug is due to line 64 in org.preesm.model.pisdf/src/org/preesm/model/pisdf/util/VertexPath.java
The vertex name is removed from the path if vertex name starts with graph name.

Now trying to figure out a fix.
