### ISSUE TITLE
Can't generate SRDAG if Broadcast Actor output rate is 0.

### ISSUE THREAD

**Issue by hmiomand** [preesm/preesm#273]
SRDAG generation fails if a **Broadcast Actor** as an output with a rate of 0.
Provided is a simple **.pi** file with a **Broadcast Actor** with a 0 rate output with which a SRDAG can't be generated.

[BrRateZero.zip](https://github.com/preesm/preesm/files/3940104/BrRateZero.zip)

**Comment by ahonorat** [comment]
This bug is fixed, but while investigating it, we discover another one related to rates being 0 : the repetition vector is not always correct in this case. This is because current repetition vector computation uses DFS while it should not. We have to update the computation with code of Spider 2.0.

**Comment by hmiomand** [comment]
For the following project, the BRV computation is indeed wrong with rates equal to zero.
Also, the code generation errors since the emetteur acteur has no more output fifo (recepteur2 is not fired).

[dummy_project_BRV.zip](https://github.com/preesm/preesm/files/3944217/dummy_project_BRV.zip)

**Comment by ahonorat** [comment]
The repetition vector computation has been updated with this new behavior: rates being zero on both sides are allowed, and ports having a rate equal to 0 on special actors are automatically removed if at least one non zero port remains.
This allows to discard full paths without firings in the graph if these paths are delimited by broadcast/roundbuffers for example.
