### ISSUE TITLE
Out of date warning about actor refinement inconsistency.

### ISSUE THREAD

**Issue by hmiomand** [preesm/preesm#274]
In the **PiMM Diagram Editor**, warnings **"Ports are out of sync with the refinement"** are still displayed after the actor having its refinement removed.

Step to reproduce:

1. Create an actor with some data ports.
2. Give it a corresponding refinement.
3. Clear the refinement.
4. Add/remove a data port.

Or:

1. Copy/paste an actor.
2. Clear the refinement.
3. Add/remove a data port.

A warning will now be displayed on the actor, indicating that **"Ports are out of sync with the refinement"**, which doesn't exist anymore.
The only way to remove the warning seems to be to assign a new refinement corresponding to the actor layout.

**Comment by ahonorat** [comment]
Error was due to an incorrect behavior of the "Clear refinement" feature: setting the refinement file to ```null``` instead of setting the refinement itself to ```null```.
