### ISSUE TITLE
[Bundled release] Run as menu and workflow task properties instability

### ISSUE THREAD

**Issue by kdesnos** [preesm/preesm#28]
In the bundled release of preesm generated by the not-yet-public jenkins server:
- "Runs as" option in the right-click menu disappear after its first use.
- Properties of the workflow tasks accessed through the workflow editor sometimes also disappear.
- *.pi files are not visible in the package explorer.

**Comment by antoine-morvan** [comment]
Could you confirm this is still valid with new product releases ?
See http://preesm.sourceforge.net/gensite/products/latest/

**Comment by kdesnos** [comment]
It seems OK.

**Comment by antoine-morvan** [comment]
It's actually still the case when installing from update site with latest version.

**Comment by antoine-morvan** [comment]
There is now a new menu entry in the Preesm context menu to run workflows. Also the context menu within the graphical editor now allows to run a workflow.
