### ISSUE TITLE
No replacement found for DataInputPort of hierarchical actor

### ISSUE THREAD

**Issue by hmiomand** [preesm/preesm#281]
Trying to compute the SRDAG of the attached project displays the error:
"No replacement found for DataInputPort [out] of hierarchical actor [subGraph]."

[dummy_srdag.zip](https://github.com/preesm/preesm/files/4040888/dummy_srdag.zip)

**Comment by ahonorat** [comment]
This is not a bug, almost all the rates where equal to 0 in the .pi graphs. Rates equal to 0 may create inconsistencies, which is the case for these graphs.
