### ISSUE TITLE
Data input interface Memory Annotation not persisting

### ISSUE THREAD

**Issue by hmiomand** [preesm/preesm#289]
Selecting a data interface by clicking on its name, then changing its associated **Memory Annotation**, won't keep the modification.
The **Memory Annotation** need to be set by selecting the interface by clicking on the colored square for the modification to be kept.

**Comment by ahonorat** [comment]
This kind of feature also exists for delays. What it does is, in general, automatically done when you set the memory annotation in the properties view: it immediately stores the view value in the model. It is kind of useless but this feature is added automatically by the GUI library in the menu. It is possible to remove it by modifying the application design.

In any case, memory annotations are probably useless on interface ports, we might also consider to not show the annotation in the properties view. This is easily doable. @kdesnos is is ok?

**Comment by kdesnos** [comment]
Yes, removing the annotations on port of hierarchical actors may be a good idea since they're most likely ignored in the workflow anyway.

**Comment by ahonorat** [comment]
Solution choose: GUI does not display the memory annotation of interfaces, and of ports of hierarchical actors. The model still stores these informations.
