### ISSUE TITLE
Generate optimized flat using UI method

### ISSUE THREAD

**Issue by orlyn44** [preesm/preesm#294]
When generating flat graph from UI using the right click contextual menu, non-optimized flat graph is generated on first call. 
To have optimized graph, it is necessary to apply the flat transformation on the first obtained flat graph.
It would be nice to produce both results at the same time.

**Comment by ahonorat** [comment]
Fixed in branch malleableParameters. Will be merged in develop in a few weeks.
New bahavior : produces both unoptimized and optimized graph at once. If the graph is already flat, the unoptimized version is not produced.
