### ISSUE TITLE
(Gantt) [release] JVM crash when right-clicking

### ISSUE THREAD

**Issue by vmorillon** [preesm/preesm#303]
OS: Ubuntu 18
Java version: openjdk 11.0.6 2020-01-14
preesm: release 3.19

Right-clicking anywhere (or waiting the information pop-up after zooming) on the Solution Gantt crash the eclipse JVM and throw the following error message:

![image](https://user-images.githubusercontent.com/61963691/76421886-a0b19380-63a4-11ea-8823-03e4b3e0aa11.png)

**Comment by ahonorat** [comment]
I think this bug appears because Preesm 3.19 uses the version 4.09 of Eclipse.
I hope that modifying dependencies in the Maven build to the upcoming Eclipse 2020-03 will solve the problem.

@jheulot can you change the Eclipse dependency once the new Eclipse release will be out?

**Comment by ahonorat** [comment]
@vmorillon confirmed me that commit 4eb3c44 fixes the issue.
