### ISSUE TITLE
(GUI) Header parsing failing on windows

### ISSUE THREAD

**Issue by kdesnos** [preesm/preesm#328]
When trying to set the refinement of an actor using either the drag-n-drop feature, or the browse button in the actor properties, nothing happens on windows. (In particular, the wizard that makes it possible to select the appropriate function never appears.)

**Comment by kdesnos** [comment]
Wasn't this fixed by the unmerged branch [fixHeaderURIParser](https://github.com/preesm/preesm/tree/fixHeaderURIParser)

**Comment by ahonorat** [comment]
Is it different from issue #324 ?

**Comment by ahonorat** [comment]
Apparently not. Fix has been released in release 3.21.0
