### ISSUE TITLE
"Export to SVG" Feature *is* broken (silent error)

### ISSUE THREAD

**Issue by ahonorat** [preesm/preesm#346]
The menu command "Export to SVG" available on PiMM diagram elements fails silently.
In dev mode, the error is reported in the console of the launching Eclipse:
```
!ENTRY org.eclipse.graphiti.ui 4 0 2021-10-29 15:52:15.195
!MESSAGE GFCommandStack.execute(Command) java.lang.IllegalArgumentException: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
!STACK 0
java.lang.IllegalArgumentException: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
	at org.apache.xerces.jaxp.DocumentBuilderFactoryImpl.setAttribute(Unknown Source)
	at org.preesm.ui.pisdf.features.SVGExporterSwitch.exportPiGraphToSVG(SVGExporterSwitch.java:171)
	at org.preesm.ui.pisdf.features.ExportSVGFeature.execute(ExportSVGFeature.java:138)
	at org.eclipse.graphiti.features.custom.AbstractCustomFeature.execute(AbstractCustomFeature.java:77)
	...
```

**Comment by ahonorat** [comment]
Here is an ugly patch to fix this bug, a better solution should be found for prod.
[badlyFixSVGexport.zip](https://github.com/preesm/preesm/files/7704489/badlyFixSVGexport.zip)

See https://stackoverflow.com/questions/58374278/org-xml-sax-saxnotrecognizedexception-property-http-javax-xml-xmlconstants-p

**Comment by ahonorat** [comment]
Ok, I understand why we did not detect this error earlier:
1. RCPTT test checking the SVG export feature [tests/org.preesm.tests.ui.rcptt/pisdf/testExportSVGFeature/exportSvgFeatureTest.test](https://github.com/preesm/preesm/blob/bf4e2a2bfddc9c5d427c834be78cf9cbd728e3b7/tests/org.preesm.tests.ui.rcptt/pisdf/testExportSVGFeature/exportSvgFeatureTest.test) has no verification test checking the creation of the "Untitled.svg" exported file.
2. Commit 78bc2f0 was intended to fix vulnerability on  plugins/org.preesm.ui.pisdf/src/org/preesm/ui/pisdf/features/SVGExporterSwitch.java and other files, but doing so it broke the feature due to the stackoverflow bug  linked in my previous comment https://github.com/preesm/preesm/issues/346#issuecomment-992533696.

Not only the bug should be fixed, but also the test.

**Comment by hmiomand** [comment]
Unable to reproduce as of #388.
Closing issue.
