### ISSUE TITLE
Unable to build the Eclipse product from either Eclipse or Maven

### ISSUE THREAD

**Issue by hmiomand** [preesm/preesm#352]
When following the tutorial from the [PREESM website](https://preesm.github.io/docs/buildpreesm/#from-eclipse) to build the Eclipse product from Eclipse, the build step fails with the following error:

![image](https://user-images.githubusercontent.com/26252258/151145357-359e413c-b782-4912-8000-f66acb12bfc8.png)

Trying to build it with Maven gives the following error:
`[ERROR] Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'Eclipse' from location http://ftp.halifax.rwth-aachen.de/eclipse//releases/2019-09/: Unable to read repository at http://ftp.halifax.rwth-aachen.de/eclipse//releases/2019-09. Unable to read repository at http://ftp.halifax.rwth-aachen.de/eclipse/technology/epp/packages/2019-09/compositeContent.xml. Read timed out`

http://ftp.halifax.rwth-aachen.de/eclipse/technology/epp/packages/ does not contain a "2019-09" directory anymore, neither does any other eclipse mirror provided in the pom.xml. The oldest package present is "2021-09".

**Comment by jheulot** [comment]
The Aachen repository remove from time to time old dependencies. 
As a temporary fix, you can try the following site by changing the eclipse.mirror var in main pom.xml:
https://ftp.fau.de/eclipse/

**Comment by hmiomand** [comment]
The issue is the same. This mirror doesn't have a "2019-09" directory within the http://<ftp>/eclipse/technology/epp/packages/.

(Tried with Maven)
`No repository found at https://ftp.fau.de/eclipse/technology/epp/packages/2019-09`

**Comment by hmiomand** [comment]
Generation of product through Eclipse is now considered unsupported.
Generation of product through Maven works as of #360.
