### ISSUE TITLE
Unable to install PREESM Developper Requirements (Meta Feature) in Eclipse 2022-03

### ISSUE THREAD

**Issue by ahonorat** [preesm/preesm#355]
While installing PREESM sources in Eclipse 2022-03 as a contributor, I got the following error:

> Cannot complete the install because one or more required items could not be found.
  Software being installed: PREESM Developper Requirements (Meta Feature) 3.2.4 (org.preesm.dev.feature.feature.group 3.2.4)
  Missing requirement: PREESM Developper Requirements (Meta Feature) 3.2.4 (org.preesm.dev.feature.feature.group 3.2.4) requires 'org.eclipse.equinox.p2.iu; org.sonarlint.eclipse.feature.feature.group 0.0.0' but it could not be found

See PREESM documentation: https://preesm.github.io/docs/buildpreesm/#install-development-requirements

**Comment by hmiomand** [comment]
This issue is probably linked to #352.

**Comment by hmiomand** [comment]
This problem is solved as of #360.
