### ISSUE TITLE
[Workflow] Implement a check that verifies that an SDF graph is deadlock free

### ISSUE THREAD

**Issue by skanur** [preesm/preesm#39]
The method `isSchedulable` and `validateModel` checks if the SDF graph has Periodic Admissible schedule. However, there is no check to verify that the graph is deadlock free (due to improper delay initialization) until DAG is created. The enhancement here is to integrate deadlock check during validation check. Reference: #38 and #19 . 

Two ways of implementing it:
1. Generate a DAG at the verification stage to check if it has any cycles
2. "Simulate" the SDF graph. A method to simulate is given in [page 5, Tripakis2013](https://doi.org/10.1145/2442116.2442133). Paper is available [here](http://www.dtic.mil/get-tr-doc/pdf?AD=ADA538756).

**Comment by ahonorat** [comment]
The requested menu popup action has been added by b13b3a142fd5ff9cdcd8f315c0853dbac9fc9c65 .
The name is "Check PiSDF Liveness".
The method used is checking if flat PiSDF is acyclic first, if no then the SRDAG is generated and again checked if acyclic.
