### ISSUE TITLE
[UI] Editing Data In/Out Interface Rate Expression

### ISSUE THREAD

**Issue by orlyn44** [preesm/preesm#43]
Editing of the data output interface is not consistent with the rest of edition.
You can only edit it through the connected fifo and not directly whereas you can do either on normal actors.

**Comment by antoine-morvan** [comment]
Actually when you select the Data In/Out Interface, it selects the Actor and not the Port, therefore you cannot edit its expression. Since data interfaces consists in one port only, it would make sense to allow editing the expression directly from the Actor property tab.
