### ISSUE TITLE
[UI] Assigning parameters to delays

### ISSUE THREAD

**Issue by orlyn44** [preesm/preesm#44]
Impossible to assign new parameter to a delay (create a dependency from Parameter to Delay) after deleting previous one without first assigning a scalar value to it.

This is due to the error icon appearing on top of the delay.

**Comment by antoine-morvan** [comment]
Workaround in https://github.com/preesm/preesm/commit/95b02cbc263e1379ee4e1e914c7d07234e049562 : move the decorator a bit so that users can drop the end of the dependency on the delay
