### ISSUE TITLE
Singlerate optimize implode broadcast explode

### ISSUE THREAD

**Issue by judicael35** [preesm/preesm#5]
Hello,

This is an idea for optimization in singlerate graph. It could be add to the one created by @ClementGGuy in commit a964c7f (org.ietr.preesm.algorithm.optimization).

Supposes you have this : 

![imp_broad_exp](https://f.cloud.github.com/assets/6907192/2497270/f7ec389e-b333-11e3-9cf2-5353884ba6e3.jpeg)

Edges size are (in this example) : 
- producers' edges (`p1` and `p2`) are the same size `size`.
- consumers' edges (`c1` .. `c6`) are the same size `size`.
- `implode_2`  out edge's size is `2*size`.
- `brocast_x3` out edeg's size is `6*size`. 

There are no delay on edges.
This example could be generated with two recursive hierarchy levels :-).

You cloud simplify this by : 

![broads](https://f.cloud.github.com/assets/6907192/2497358/74ca03c2-b335-11e3-87ea-64552e6f777e.jpeg)

All edges are the same size `size`.

This example is applicable to any similar problems with with `n` producers which are imploded and broadcast `b` times. The size of producers and consumers are not necessary the same. And the consumers size too. The constraints is `size(p)*b = sum(size(c(p)))` where : 
- `size(p)`is the size of one producer.
- `c(p)` are all consumers associated to producer p.

This conditions must be true for all producers. The association producer/consumer is done by order.

Someone more "expert" in preesm that I am (like @kdesnos :-)) should give it opinion on those conditions.

Advantages of this optimization is more freedom for schedulers optimization, and possibility of memory optimization on broadcast thanks to @kdesnos pure_in memory optimization.

**Comment by antoine-morvan** [comment]
See #45
