### ISSUE TITLE
Non standard schedulers (*fast* and *pfast*) produce runtime exception

### ISSUE THREAD

**Issue by ahonorat** [preesm/preesm#57]
Two scheduling/mapping algorithms produce a runtime exception (NulllPointerException) when used with the default parameters on regular single rate graphs. The faulty algorithms identifiers are:
- org.ietr.preesm.plugin.mapper.fast
- org.ietr.preesm.plugin.mapper.pfast
respectively in the packages:
- org.ietr.preesm.mapper.alog.fast
- org.ietr.preesm.mapper.algo.pfast

**Comment by antoine-morvan** [comment]
Could you provide a minimal example to reproduce ?

**Comment by antoine-morvan** [comment]
These schedulers are deprecated and will be re-implemented in the future coming scheduling API.
