### ISSUE TITLE
group deletion

### ISSUE THREAD

**Issue by orlyn44** [preesm/preesm#58]
Doesn't do anything when trying to remove a mixed group of parameters and actors.
When removing a group composed only of actors, it works fine. Same for parameters.
The issue raises in the specific case of trying to remove parameters and actors in the same selected group.

**Comment by orlyn44** [comment]
The problem is a bit more specific than expected. 
The bug seems to happen when a delay is in the selection group.

**Comment by orlyn44** [comment]
[delay.pi.zip](https://github.com/preesm/preesm/files/1828614/delay.pi.zip)

**Comment by antoine-morvan** [comment]
I could not reproduce the issue with the provided example. Has it been solved with more recent versions ?

**Comment by antoine-morvan** [comment]
@orlyn44 please reopen if you can provide an example to reproduce with latest versions.
