### ISSUE TITLE
Singlerate simplify roundbuffer

### ISSUE THREAD

**Issue by judicael35** [preesm/preesm#6]
This is an idea for optimization in singlerate graph. It could be add to the one created by @ClementGGuy in commit a964c7f (org.ietr.preesm.algorithm.optimization).

When using iterative dataflow, that kind of structure is generated :

![round_buffer](https://f.cloud.github.com/assets/6907192/2497781/9f82057c-b33c-11e3-88e2-55c458978c3a.jpeg)

In this example, all edges size are the same. There is a delay of edge size between `b3` and `c3`.

A producer and consumer are generated for each step (generally, the producer of a step is the consumer of previous step). And intermediates result are broadcasted to next iteration, and a round buffer. The goal of round buffer is to take the last iteration value. I propose to simplify it by : 

![round_buffer_opt](https://f.cloud.github.com/assets/6907192/2497874/eb382cde-b33d-11e3-8201-c6f2c65d00be.jpeg)

The delay still existing between `b3`and `c3`.

The pros of this optimization are : 
- Lower memory usage (Intermediates steps are no more kept).
- Decrease the number of broadcast (easiest scheduling and memory mapping).

**Comment by antoine-morvan** [comment]
See #45
