### ISSUE TITLE
Impossible to set .pi refinement after clearing .h refinement

### ISSUE THREAD

**Issue by orlyn44** [preesm/preesm#69]
After clearing a .h refinement of an actor, it is not possible to set a new .pi refinement.
It is however possible to set an other .h refinement.

Test case:
      - Select an actor with .h refinement.
      - Use the clear button to remove the refinement
      - Try to set a .pi refinement --> Nothing happens (no message in the debug console of PREESM either)

**Comment by antoine-morvan** [comment]
merged on develop.
