### ISSUE TITLE
Scenario Editor: Issue in Timing tab when a hierarchical subgraph is instantiated multiple times.

### ISSUE THREAD

**Issue by kdesnos** [preesm/preesm#77]
In the timing tab, if an actor is instantiated multiple times in hierarchical subgraphs of the application, for example if a hierarchical subgraph is instantiated several times, multiple lines of the _Timings_ tab will be displayed for this actor. Editing the timing value of any of these lines also changes the value of all others. In the top level graph, there is still a separate line for each instance of a same actor (i.e. actors with the same refinement).

Currently, the policy of this editor is that one line is displayed per actor instantiation, allowing the user to set on timing per actor instance instance per core type. The timing editor should either be made fully compatible with this behavior, by differentiating the actors of each subgraph instance, or allow the value of timing to be expressions, as requested in Issue #73.

Maybe a hybrid system enabling both per instance OR expression-based timing specification would be more flexible for the user.

**Comment by antoine-morvan** [comment]
see https://github.com/preesm/preesm/issues/132
