### ISSUE TITLE
Problem with the "Number of executions of the top-level graph" 

### ISSUE THREAD

**Issue by ClaudioRubattu** [preesm/preesm#87]
It seems that the number of executions remains always equal to one during the simulation, and the LOOP_SIZE doesn't seem properly defined.

**Comment by antoine-morvan** [comment]
The number of executions in the scenario is not related to the PREESM_LOOP_SIZE parameter in the generated code. Documentation has been updated regarding the PREESM_LOOP_SIZE parameter: https://preesm.github.io/docs/workflowtasksref/#code-generation-1

As for the value set in the scenario, it will be removed soon.
