### ISSUE TITLE
(Gui) Out of sync

### ISSUE THREAD

**Issue by kdesnos** [preesm/preesm#91]
When editing a graph, error tend to occur, causing the pi to be out of sync with the diagram, and the diagram to be not "saveable".

**Comment by kdesnos** [comment]
To reproduce, follow tutorial on sobel and toy around by adding and removing actors and fifo without saving the graph in the middle. This should do the trick.

**Comment by LowellHuawei** [comment]
Yes, I think my problem is related to this.

Sometimes detecting and fixing problems can be very difficult.  One possible way to alleviate the pain of this kind of problem, where 2 files get out of sync, is to make the save code write to temporary files and then only if both are successfully saved, delete the originals and rename the new saved copy.  It doesn't fix the problem, but it alleviates the fairly fatal error of having the project totally unusable after the event.
