### ISSUE TITLE
(Codegen)  Instrumented codegen has incorrect columns in analysis.csv.

### ISSUE THREAD

**Issue by kdesnos** [preesm/preesm#95]
Following the C6678 tutorial and the instrumented codegen one, it seems that the columns used to compute the time of actors are not the right ones.

**Comment by antoine-morvan** [comment]
Same as https://github.com/preesm/preesm/issues/52

@ahonorat  Is it still an issue since latest **dump.h** ?

**Comment by antoine-morvan** [comment]
see https://github.com/preesm/preesm/issues/132
